name: Build and Release ESP32 Firmware

on:
  push:
    tags:
      - 'v*' # Trigger only when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build ESP-IDF project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32s3  # Change to esp32s3, esp32c3, etc., if needed

      - name: Get Short Git Hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.bin
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Firmware Details
            - **Version:** ${{ github.ref_name }}
            - **Commit Hash:** [${{ steps.vars.outputs.sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - **Build Date:** ${{ github.event.head_commit.timestamp }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}